version: '3.2'
services:
  opencv:
    container_name: opencv-example-2
    # image: marcosricardoss/raspbian-opencv:latest 
    image: jumidlej/opencv:python3.8
    command: python3.8 -u usr/src/app/app.py
    volumes:
      - './:/usr/src/app'
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices: 
      - /dev/vchiq:/dev/vchiq # PiCamera
      - /dev/vcsm:/dev/vcsm # VideoCore Shared Memory (VCSM)
    environment:
      - DISPLAY=$DISPLAY
    privileged: true

# $DISPLAY environment varible and .X11 volume specify 
# the Docker container to share the X11 socket and host display.
# The command 'xhost +', that allows any client to connect from any host,
# must be executed before the container 'up' command (like bash script file bin/dev).
